name: Run tests
on:
  push:
    branches:
      - master
      - security-validator
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
    branches:
      - master
      - security-validator
jobs:
  run-tests:
    if: github.event.pull_request.draft == false
    name: Run automated tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up env vars
        run: |
          echo "GO111MODULE=on" >> $GITHUB_ENV
          echo "CHANGE_MINIKUBE_NONE_USER=true" >> $GITHUB_ENV
          echo "MINIKUBE_WANTUPDATENOTIFICATION=false" >> $GITHUB_ENV
          echo "MINIKUBE_WANTREPORTERRORPROMPT=false" >> $GITHUB_ENV
          echo "GO_VERSION=v$(sed -n 's/GO_VERSION=//p' config.base.env)" >> $GITHUB_ENV
          echo "HELM_VERSION=v$(sed -n 's/HELM_VERSION=//p' config.base.env)" >> $GITHUB_ENV
          echo "GOPATH=/home/runner/go" >> $GITHUB_ENV

      - name: Prepare go environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Ensure Golang runtime dependencies
        run: make go-dependencies

      - name: Verify code formatting
        run: make verify

      - name: Prepare environment for e2e
        run: |
          sudo apt-get update
          sudo apt-get install socat
          sudo mkdir -p $HOME/.kube $HOME/.minikube
          sudo chown -R $USER $HOME/.kube $HOME/.minikube
          make minikube-start MINIKUBE_DRIVER='docker' CPUS_NUMBER=2

      - name: Jenkins Operator - e2e
        run: make e2e E2E_TEST_ARGS='-ginkgo.v'

      - name: Jenkins Operator - Helm Chart tests
        run: |
          git reset --hard
          make helm-lint
          eval $(bin/minikube docker-env)
          make helm-e2e E2E_TEST_ARGS='-ginkgo.v'
